### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by redboy1972** [Netflix/dynomite#120]
https://github.com/Netflix/dynomite/blob/master/README.md

I am brand spankin' new to Dynomite and there are some things that causes me as a new user to be confused.  I wanted to point them out so that you can update the documentation to be more new user friendly.  I can't do this myself as I don't know the answers.

> env: Specify environment of a node. Currently supports aws and network (for physical datacenter).
> What is the difference and why should I choose one over the other.
> 
> dyn_listen: The port that dynomite nodes use to inter-communicate and gossip.
> This seems to be a "IP:PORT" combo and is misleading.
> 
> tokens: The token(s) owned by a node. Currently, we don't support vnode yet so this only works with one token for the time being.
> Not sure what a token is, what to set it to, how it works in grand scheme of things, etc.  In examples some seem to share this, some don't.  Confused.  I think it represents the range of hash values this server will process.
> 
> dyn_seed_provider: A seed provider implementation to provide a list of seed nodes.
> Not sure what this is but plan to leave as default as other options are unknown.
> 
> dyn_seeds: A list of seed nodes in the format: address:port:rack:dc:tokens (node that vnode is not supported yet)
> Instead of referring them to seed nodes is it better to have them described as location of other servers.  At least in my naive understanding that's how I see them.
> 
> listen: The listening address and port (name:port or ip:port) for this server pool.
> This seems to be the "IP:PORT" to use in a multihomed environment then "this server pool" is added and now I am totally confused.
> 
> server_connections: The maximum number of connections that can be opened to each server. By default, we open at most 1 server connection.
> Is this Client -> Server traffic or gossip channel? Seems gossip as "we open" is in there.
> 
> servers: A list of local server address, port and weight (name:port:weight or ip:port:weight) for this server pool. Usually there is just one.
> This overlaps some previous comments.  "Server pool", "token".  How does this differ from "listen"

Explain connection pools
Better explain tokens...  I found this "Each node in a rack has a unique token, which helps to identify which dataset it owns." By itself it is ok but when it comes to setting it to some value in the file I am lost.

---

These seem missing but have found them in example configuration files online.
backlog: 1024
distribution: vnode
hash: murmur

**Comment by timiblossom** [comment]
Thanks - we will rework on the documents for sure.

**Comment by vpopescu** [comment]
As another brand-spanking new user, I'd also request you bring the command line options list up to date. For example, there is a "-g" option to enable gossip which I don't understand since I thought gossip was fundamental to dyanamo.

And if I turn it, on, bad things happen. But I'm not sure I'm understanding what -g should do and how it's affected by my config file.

[Thu May 21 15:37:52 2015] dyn_util.c:299 free(0x7f57b8115790) @ dyn_dict.c:614
[Thu May 21 15:37:52 2015] dyn_util.c:253 malloc(48) at 0x7f57b8115790 @ dyn_dict.c:552
[Thu May 21 15:37:52 2015] dyn_util.c:320 [0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x10d10) [0x7f57be083d10]
[Thu May 21 15:37:52 2015] dyn_util.c:320 [1] dynomite(dictFingerprint+0x4) [0x42a364]
[Thu May 21 15:37:52 2015] dyn_util.c:320 [2] dynomite(dictNext+0xd8) [0x42a588]
[Thu May 21 15:37:52 2015] dyn_util.c:320 [3] dynomite() [0x428cd4]
[Thu May 21 15:37:52 2015] dyn_util.c:320 [4] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76aa) [0x7f57be07a6aa]
[Thu May 21 15:37:52 2015] dyn_util.c:320 [5] /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f57bdaa7eed]
[Thu May 21 15:37:52 2015] dyn_signal.c:127 signal 11 (SIGSEGV) received, core dumping

...

Program terminated with signal SIGSEGV, Segmentation fault.
#0  dictFingerprint (d=d@entry=0x1000074) at dyn_dict.c:522
522         integers[0] = (long) d->ht[0].table;
(gdb) bt
#0  dictFingerprint (d=d@entry=0x1000074) at dyn_dict.c:522
#1  0x000000000042a588 in dictNext (iter=0x7f96d4115790) at dyn_dict.c:579
#2  0x0000000000428cd4 in gossip_forward_state (sp=<optimized out>) at dyn_gossip.c:209
#3  gossip_loop (arg=0x1000074) at dyn_gossip.c:760
#4  0x00007f96dbadd6aa in start_thread (arg=0x7f96da9fe700) at pthread_create.c:333
#5  0x00007f96db50aeed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by timiblossom** [comment]
@vpopescu we will fix this asap.  Please run it with disable gossip and use the local service for now.  Those 2 are kind of interchangeable.

**Comment by ipapapa** [comment]
@akbarahmed @shailesh33 since we are now doing the work to update YAML https://github.com/Netflix/dynomite/issues/368 this might be related. Some folks seem to be confused about the terminologies. Any recommendation on how to better organize the documentation? There is some good advice from @redboy1972.

**Comment by akbarahmed** [comment]
@ipapapa @shailesh33 I agree. Are you thinking about changing just the yaml variables, just the documentation, or both?

**Comment by ipapapa** [comment]
@akbarahmed there two parallel efforts. One by you #368 and one by me #370 where we are changing the YAML and the documentation. I think as long as the basic functionalities are backward compatible we should update both... I was curious though on what would be the best plan?

**Comment by akbarahmed** [comment]
@ipapapa I've posted some thoughts on the yaml options at https://github.com/Netflix/dynomite/issues/368.

I'm okay with deferring to you on the yaml updates since you're already working on it.

**Comment by ipapapa** [comment]
It seems we have a good discussion in https://github.com/Netflix/dynomite/issues/368 about renaming the YAM entries. The gossip enabler argument has also moved to the YAML https://github.com/Netflix/dynomite/pull/386 as well as other entries https://github.com/Netflix/dynomite/pull/387. Hence I think we have addressed this issue. If there are any further questions, we can reopen it.
