### ISSUE TITLE
why dynomite not check redis status

### ISSUE THREAD

**Issue by xichehe** [Netflix/dynomite#158]
I have two rack(rack1 rack2) and each have four node & four redis service,
I set & read data from random rack with phpredis extension.
I have simple tactics for failing over：if find some dynomite node not connect,i set all node for same rack is fail,next redis request will avoid connect bad node. well,It worked out Fine.

if all dynomite rack status is ok,i turn off any backend redis service,
the above failing over tacticsout of work: connect dynomite node is ok,but i will missing get & set some data.

how can known  backend redis status by dynomite? dynomite node have some auto heath check for redis?

**Comment by ipapapa** [comment]
If Dynomite cannot send a request to Redis it should be reported in the log files. Moreover, there are some health check stats printed out as a JSON file in port 22222 (you see them from your browser http://node_ip:22222/info). Did you check them?

**Comment by mfouilleul** [comment]
"how can known backend redis status by dynomite"

By the command PING no?

Max

**Comment by xichehe** [comment]
ping or curl Dynomite node to check  backend redis status,before every client set/get key request?

**Comment by ipapapa** [comment]
Your application should have a failover strategy based on the exception.  For example, 
GET/SET with Redis down/Dynomite up ---> "(err) ERR Storage: Connection Refused". 
GET/SET with Dynomite down ---> "Could not connect to Redis at ip_address:port_number: connection refused"

**Comment by ipapapa** [comment]
@xichehe has your issue been answered?

**Comment by xichehe** [comment]
when  GET/SET with Redis down/Dynomite up,  my code can't get some  exception use phpredis extension~,need some server side config?
if Dynomite up,backend redis is down, why Dynomite route route client request to bad redis service,why not  Connection Refused?

**Comment by ipapapa** [comment]
Dynomite does return two different error messages for each case. The reason that Dynomite does not return "connection refused" is because the client is able to establish a connection with Dynomite even if Redis is down. It is up to the client API to capture the error message from Dynomite and throw the proper exception to the application. Other clients return the proper exceptions (e.g. redis-py, redis-cli etc.). phpredis seems to throw a RedisException only if the server is unreachable (overloaded, Dynomite is down, connectivity issues): https://github.com/phpredis/phpredis#class-redisexception 
If Dynomite is reachable and Redis is down, phpredis may return FALSE (based on the documentation, I have not tested it).

**Comment by xichehe** [comment]
thx ipapapa!

**Comment by ipapapa** [comment]
This is not the case. For every command that is issued towards Dynomite with Redis down the exception will appear on the cli: ERR Storage: Connection Refused. Did you start redis-cli with the dynomite port: i.e. -p 8102?
