### ISSUE TITLE
Has it support scale out the rack and recover data automatically?

### ISSUE THREAD

**Issue by wuyingfengsui** [Netflix/dynomite#173]
#69 and #51 seem like dynomite doesn't support scale out the rack and recover data automatically. If I missed something let me know.

**Comment by mfouilleul** [comment]
Right, for now dynomite is a query routing + replication system. It does not manipulate the dataset itself for rebalancing or warmup the backends, you should manage this part.

**Comment by ipapapa** [comment]
@wuyingfengsui we are working on automatic data reconciliation. However, as @mfouilleul said you can manage it manually with a side script, especially given the latest consistency feature. We will also be glad to accept any patch or script that assists towards this effort.

**Comment by mfouilleul** [comment]
It could be a good idea to share this kind of scripts. Do you know if the stat commands writes_only, resuming are still used? 

Max.

**Comment by ipapapa** [comment]
@mfouilleul yes it is there: https://github.com/Netflix/dynomite/blob/master/src/dyn_stats.c#L1130-L1132

**Comment by timiblossom** [comment]
@wuyingfengsui you can manually add a node by doing these:
1-pick a position or range in ring between 2 nodes to add a new node
2-That data range should be owned by left node (if I remember correctly or otherwise it is the right node)
3-Take a Redis dump from that left node and copy this data to the new node
4-Fix dynomite config file and start dynomite on the new node and the left node with "-x 1" option
5-For each key for the data set, use this script 
    https://github.com/Netflix/dynomite/blob/master/scripts/dyn_redis_test.py
  to send a write request for that key.  With "-x 1" option, Dynomite will remove any key and its data out of 
  its local Redis if the key does not fall into its range.
6- Restart Dynomite processes on those 2 nodes without "-x 1" option.

This process requires some downtime and manual steps.  In addition, you can play with stat commands writes_only command as @mfouilleul mentioned to temporarily storing incoming writes during the maintaining time before flushing them out to Redis from Dynomite.

We are still working on a better way to automate this.

**Comment by wuyingfengsui** [comment]
Thank you. Looking forward these new features.

**Comment by mfouilleul** [comment]
@ipapapa about stat commands, I saw them in the code but it does not seems to have any impact on my instance:

````
root@dyno1:~# dynomite --version
This is dynomite-0.5.3 
```

```
root@dyno1:~# redis-cli -p 8102
127.0.0.1:8102> set test mytest
OK
127.0.0.1:8102> get test
"mytest"
```

```root@dyno1:~# curl http://127.0.0.1:22222/state/standby
OK
root@dyno1:~# redis-cli -p 8102 get test
"mytest"
root@dyno1:~# redis-cli -p 8102 set test mytest2
OK
```

May I doing something wrong?

Max.

**Comment by mfouilleul** [comment]
Ok, i found why.

It does not work with 127.0.0.1

```
root@dyno1:~# curl http://dyno1:22222/state/standby
OK
root@dyno1:~# redis-cli -p 8102 get test
(error) ERR Peer: Resource temporarily unavailable
```

```
root@dyno1:~# curl http://dyno1:22222/state/normal
OK
root@dyno1:~# redis-cli -p 8102 get test
"mytest2"
```

**Comment by ipapapa** [comment]
@mfouilleul seems the issue has been resolved. I will close this issue and reopen if needed.
