### ISSUE TITLE
How Netflix does Cluster Operations with Dynomite?

### ISSUE THREAD

**Issue by diegopacheco** [Netflix/dynomite#197]
Hi Guys,

I have some questions in regards of Operation point of view.

A) How to you guys add more capacity to a cluster to add new nodes on the fly? Do you have downtime? what is the procedure to do this?

B) Lets say we add 2 more nodes in 2 different data centers, how you deal with redis? Dynomite takes care of the replication or we need to migrate keys manually? 

C) Lets say a couple of nodes goes down and using auto-scaling we put the nodes up again, will this nodes get the data back when they boot up or we need deal with this as a side operation task? 

D) What are the Netflix components using Dynomite in production? How heavy are you guys using it? 

Cheers,
Diego Pacheco

**Comment by timiblossom** [comment]
@diegopacheco 

A) Currently it is possible to add nodes on the fly but you have to clean up data on impacted nodes.  For example, clean-up process to remove record b out of node A if now another node B is the owner.
We try to do the dual-write method by having clients to write to both new and old clusters and then switch out traffics to the old one and have the new cluster becomes active.
B) We are still working on Dynomite feature for this.  Use the dual write technique meanwhile
C) Currently, you can bring data back to a new node from its peer using Redis' master-slave sync.
   Or you can take a data dump from a peer, move the dump file over to the new node and start Redis.  Redis would load back the data into memory from the dump file.  Note that using this method would have some data loss.  Dynomite does have the option to receive write only data during this process and flush out the data after redis is ready.  There is another post we already addressed this question.
Meanwhile, we are working on the data repair engine that can address the data loss and will opensource it after we fully test it.
D) We have a component similar to Priam which we use to manage Cassandra cluster. Due to its dependency on our internal library, it takes us some effort to open source it so this is why we still haven't done that.  
However, without this, you can write some scripts in its place.  You probably need a script to compute a list of tokens to assign to each node which we have it under our scripts directory.  Then, you need a script to monitor whether Dynomite and Redis are still up and running and take some action otherwise.
We also have some scripts to help us running some tasks in our automation system.  

Moving forward, we plan to make Dynomite to be a self-healing system but that is still a long shot.

**Comment by ipapapa** [comment]
@diegopacheco the afforementioned scripts can be found here: https://github.com/Netflix/dynomite/tree/master/scripts

**Comment by diegopacheco** [comment]
@timiblossom @ipapapa Thanks for all the clarifications. Do you guys have run books for Winston or Stack Storm you can share?

**Comment by diegopacheco** [comment]
OH Sorry, you said self-healing system, cool :-) That`s answer my Wiston / StackStorm Question. :-)

**Comment by ipapapa** [comment]
@diegopacheco Netflix's Winston based on Stackstorm is an event-driven automation and remediation, and therefore external to the Dynomite software.  Our long-term goal, as Minh explained above, is to move some of the self-healing processes inside Dynomite. We are always looking for assistance and feedback from the community on this.

**Comment by titasbose1** [comment]
Hi @ipapapa  @timiblossom .
im working on  redis dynomite clustering , facing a scenario like this.
currently im having 2 servers serverA & serverB ,2DC in 2 servers  . my serverA went down .
all read write request came to serverB and got stored .now i manually made serverA up with redis nodes . i want to replicate serverB whole data in serverA .basically i want rebalancing between 2 DC .
How do i do that ? please help !!


i have posted question here .link : https://github.com/Netflix/dynomite/issues/770

**Comment by ipapapa** [comment]
Please take a look at the [Cold Bootstrapping](https://github.com/Netflix/dynomite-manager/wiki/Cold-Bootstraping) process. The process is fairly simple.
