### ISSUE TITLE
Questions about `florida.js` functionality

### ISSUE THREAD

**Issue by akbarahmed** [Netflix/dynomite#217]
The following questions are about how `scripts/Florida/florida.js` is designed to function. Please note that I'm asking about design goals for how the script should work, not how the script functions currently.

- Is the list of seeds in `seeds.list` static (i.e. it only changes via manual updates), or can `seeds.list` change while the http server is running? In other words, can the `florida.js` script read `seeds.list` once when the server starts or must it read `seeds.list` on each request?
- Is `florida.js` a high-volume server that is polled frequently, or is it a low volume server? Specifically, does the performance of `florida.js` matter?

I'm asking because I think there are a few updates that I would like to make to `florida.js`:

1. If `seeds.list` is static, then the script should read the file once when the server starts instead of on each request.
2. `readFileSync` should be changed to `readFile` to avoid blocking IO.
3. `console.log` is blocking and can/should be removed if the performance of `florida.js` matters. Even if performance is not an issue, I could add a `debug` flag that enables/disables `console.log`.

If these updates are agreeable, then I'll submit a pull request tonight.

**Comment by ipapapa** [comment]
I believe @diegopacheco would be the person to ask about this Node.js script. You can check #195 for the design principles as well.

At Netflix we use a sidecar called Florida developed in Java, which have not been open sourced yet. This script was developed by @diegopacheco  as an open source alternative.

**Comment by akbarahmed** [comment]
@ipapapa Thanks for the input.

@diegopacheco I have committed my updates to my forked repo. Please review. If approved, I will then submit a pull request.

You can view my proposed changes in the `async-florida` branch at https://github.com/akbarahmed/dynomite/blob/async-florida/scripts/Florida/florida.js.

I also wrote a small document on how to directly run `florida.js` (if needed): https://github.com/akbarahmed/dynomite/blob/async-florida/docs/florida.js.md

**Comment by diegopacheco** [comment]
@akbarahmed  @ipapapa 

As far I as benchmarked Dynamite I would not say Florida is a high volume service Florida. Florida receives a couple of calls, time to time, it's not a big deal. However, your points for the sake of improvements are valid - thanks for the contribution. :-) 

If you change the seeds file you will need stop Florida and start again, which is okay, I did not see problems on dynamite because of this. If you take a look on Dynomite src/seeds_provider/dyn_florida. c, you will see I added some OS_VARS so you can change Florida URL, IP and PORT, this gives you the ability to point to other servers you can write your on Florida implementation since is just a proxy. 

Cheers,
Diego Pacheco

**Comment by diegopacheco** [comment]
@akbarahmed  you changes looks ok to me.

**Comment by ipapapa** [comment]
@akbarahmed please create a pull request to dev branch. Thank you!

**Comment by akbarahmed** [comment]
@diegopacheco @ipapapa Thanks for the approval/review. I'll issue a pull request by tonight.
