### ISSUE TITLE
Is Redis pipelining supported without using Dyno?

### ISSUE THREAD

**Issue by mansoor-s** [Netflix/dynomite#288]
How does Dynomite handle pipelined Redis operations while *not* using the Dyno client? Specially when the pipelined operation uses `Hash Tags` and all of the keys in the pipeline have the same hash tag.

Does the Dynomite node that receives the operation separate out the operations and route them to the correct node responsible for that key? or does it send the whole pipelined operation to the node that is responsible for the first key in the pipeline?

Thanks

**Comment by shailesh33** [comment]
Hello Mansoor
Dynomite would be able to handle pipelines without issues. However if you are talking about python, it implements pipelining using transactions (MULTI-EXEC) so dynomite does not support that. However otherwise there should not be a problem for dynomite with pipelining.
To answer your other question, Yes Dynomite separates out the commands and routes to the right node. So every message is treated and routed seperately.

Hope this helps

**Comment by mansoor-s** [comment]
This helps a lot. Thank you!

**Comment by shailesh33** [comment]
I will close this issue. Feel free to reach out if you have more questions.

**Comment by ipapapa** [comment]
There seems to be several Python Redis clients. Some of them may not wrap MULTI/EXEC in pipelines or have it configurable. According to [pypi](https://pypi.python.org/pypi/redis)
_MULTI/EXEC: These are implemented as part of the Pipeline class. The pipeline is wrapped with the MULTI and EXEC statements by default when it is executed, which can be disabled by specifying transaction=False. See more about Pipelines below._

**Comment by gwik** [comment]
Is there a plan to support redis transations (MULTI/EXEC), with the constraint of course that all the keys used in the transaction map to the same partition ?
