### ISSUE TITLE
More storage engines

### ISSUE THREAD

**Issue by WhiteTrashLord** [Netflix/dynomite#310]
Do you have any specific plans when you will add more storage engines? I would like to test Dynomite with RocksDB :)

**Comment by ipapapa** [comment]
Yes, we have been looking into solutions about it and have done integration and performance tests with frameworks that support the [RESP](http://redis.io/topics/protocol) (REdis Protocol Specification or else Redis API). Our focus has been on RocksDB, LMDB and some others embedded databases. We are still investigating, but since you are interested to get up an running with RocksDB pretty fast you can do the following:

* Swap on server and reboot for changes to take effect *

`
sudo vi /etc/sysctl.conf
vm.swappiness = 0
sudo reboot
`

* Install a Redis compatible framework * for example [ARDB](https://github.com/yinqiwen/ardb) https://github.com/Netflix/dynomite/issues/254 or [Ledis](https://github.com/siddontang/ledisdb). 

For ARDB, you must set the storage_engine before the build. 
`
cd /apps && git clone https://github.com/yinqiwen/ardb.git
cd /apps/ardb
make
`

**Comment by WhiteTrashLord** [comment]
Sorry for the question, but I don't understand why you cannot include RocksDB directly into Dynomite. It should be faster than using the Redis protocol. If you can only support this you might change your project description to something like this: 'A generic dynamo implementation for different k-v storage engines which support RESP'.

**Comment by ipapapa** [comment]
@WhiteTrashLord there are multiple ways that you can tackle the multiple storage engine support.  Our current thinking is based on: (a) understand the differences of each of the storage engines based on our production workload patterns; (b) minimally intervene our production users that have relaxed latency requirements, but need more data store space. Given the high availability nature of Dynomite, we could simply perform a binary upgrade, and warm up the new node.

The other way is to integrate RocksDB inside Dynomite. If this is of interest to you, please feel free to assist on this endeavor. 

Addressing your last point, Dynomite can support multiple protocols. It currently supports Redis, Memcached and I had done a PoC with the [Mongo protocol](https://github.com/ipapapa/dynomiteIoannis/tree/mongodb/src/proto). In a similar manner, you can define other wire protocols.

**Comment by ipapapa** [comment]
@WhiteTrashLord let us know if you have any further questions, or if this is considered answered.
