### ISSUE TITLE
Few questions 

### ISSUE THREAD

**Issue by kunalsomani** [Netflix/dynomite#322]
1. I would like to know what is the source to generate the token? 
2. Metadata change in cluster is accessed by dyno client is push or pull model?
3. Dynomite support data rebalancing? if there is any new redis node added in cluster how the data will be rebalance? can you share the doc? 
4. Does the dynomite support resharding without restart if I add one more node into the rack?
5. Does Dyno client open the connection with every node of dynomite in cluster? If not what is the use of topology aware in client side?

**Comment by ipapapa** [comment]
These are good questions:
1. Tokens can be generated with the following [script](https://github.com/Netflix/dynomite/blob/dev/scripts/dynomite/generate_yamls.py). There are [exemplar](https://github.com/Netflix/dynomite/tree/dev/conf) configurations provided. Once you add the tokens in YAML file, these are used when you provision Dynomite. When a node dies, we need to have an external groundtruth to make sure that the new node can read the tokens from. Some folks in the OSS have developed [Florida](https://github.com/Netflix/dynomite/tree/dev/scripts/Florida) and we have provided [Dynomite-manager](https://github.com/Netflix/dynomite-manager).

2. Dyno performs a get_seeds() REST call every 30 seconds to Dynomite-manager. This ensures that dynamic changes of the topology are mapped back to the Dyno client. Hence, this enables Dyno to be token aware.

3. Dynomite does not currently provide load rebalancing. Dynomite provides [warm up](https://github.com/Netflix/dynomite-manager/wiki/Cold-Bootstraping) when a node dies and new node joins the ring. In order to scale up/down your cluster, you can use the [dual-write](https://github.com/Netflix/dyno/wiki/Dual-Write-Functionality) functionality of dyno (currently in beta).

4. Not yet.

5. Dyno opens multiple connections with all nodes in the clusters. By default it is 3.

**Comment by ipapapa** [comment]
We haven't heard back from you regarding this question. At this time, we're marking this case as Resolved. If you want to follow up with further questions let us know and we can either reopen the issue, or please create a new issue.

**Comment by kunalsomani** [comment]
Thanks for reply. Looking into more detail level and will have more question after that. Is there any other channel on which I can ask my questions?

**Comment by ipapapa** [comment]
You can use Gitter: https://gitter.im/Netflix/dynomite?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
