### ISSUE TITLE
Using Dynomite with spinnaker for cache and storage

### ISSUE THREAD

**Issue by raffian** [Netflix/dynomite#324]
In the process of deploying spinnaker clusters across two DCs, desire is to use redis for storage and cache while avoiding cassandra entirely. Posted question on spinnaker slack channel asking if Dyno client can be used with spinnaker, @tomaslin said Igor used it few years back, but due to limitations with distributed key search and LUA scripting (at the time), Dyno was dropped.

Browsing Dynomite wiki, it appears distributed key search has been addressed with scatter/gather. Regarding LUA, I'm only seeing [Issue 245](https://github.com/Netflix/dynomite/issues/245) that relates, appears to have some limitations, not sure where things stand today, or if it's sufficient for spinnakers' needs. I'll need to dig deeper into Igor code to determine feasability, nevertheless, wondering if anyone on project team can shed light on using Dyno with spinnaker,

**Comment by tomaslin** [comment]
would be better if this was implemented as a separate storage type from the existing redis implementation than replacing it. Clouddriver and orca both have significant redis implementations.

**Comment by ipapapa** [comment]
@raffian when Spinnaker was built Dynomite was in beta (that was several years ago). Since then many things have changed.

Yes, I do not currently see any limitation on why Dynomite could not replace Redis to get advantage of cross DC replication (hence using a [coordinator node](https://github.com/Netflix/dynomite/wiki/Replication)), or you can use the Dyno/Jedis wrapper to be token aware (requires replacing JedisClient with [DynoJedisClient](https://github.com/Netflix/dyno/wiki/Getting-started-with-Redis-client)). I am not aware of the internal Lua scripts of Spinnaker, but you can see more detailed information about Lua script support [here](https://github.com/Netflix/dynomite/blob/dev/notes/redis.md#scripting).

The main limitations of Dynomite is around Redis pub/sub. I briefly discussed with @tomaslin and it seems that although Spinnaker uses Spring Framework, it does not use [Spring Data Redis](http://projects.spring.io/spring-data-redis/), which inherently uses pub-sub.

**Comment by tomaslin** [comment]
except in front50 where Spring Data Redis is used but traditionally you would want to use s3 there instead of redis anyways.

**Comment by raffian** [comment]
_The main limitations of Dynomite is around Redis pub/sub. I briefly discussed with @tomaslin and it seems that although Spinnaker uses Spring Framework, it does not use Spring Data Redis, which inherently uses pub-sub._

@ipapapa 
This could be a silver lining for us if I'm understanding it correctly. We just built a geo-distributed event bus using AMQ/Java/JMS; it's essentially our cloud messaging solution. It could technically fill the pub/sub gap assuming in spinnaker the functionality is modularized to facilitate replacing the implementation.

@tomaslin 
Do you think it's feasible replacing pub/sub in spinnaker, or would it be too much effort? 
And just to be clear, since "pub/sub" is generic, please reference an example in spinnaker where/how it's being used; is it essentially the Observer/Observable code?

**Comment by ipapapa** [comment]
@raffian any plans on moving forward with this? I was wondering whether to leave the issue open or close it. I am assuming a potential PR will go towards the Spinnaker projects.

**Comment by raffian** [comment]
I want to explore this in the future, for now you may close this issue.
