### ISSUE TITLE
Sidekiq unsupported, redis_parse_req:1223 parsed unsupported command 'brpop'

### ISSUE THREAD

**Issue by jonakoudijs** [Netflix/dynomite#417]
We use Sidekiq with our application. Sidekiq relies heavily on Redis. Sadly it uses the following command: 'brpop', which is not supported by Dynomite. Would it be possible to add such an command and/or use Sidekiq at all with Dynomite?

In the meantime I will go through the Sidekiq code and check if there any other unsupported commands that Sidekiq uses by default.

**Comment by jonakoudijs** [comment]
We checked the Sidekiq code and sadly the following unsupported commands are also used by Sidekiq:

- brpop
- flushdb
- info
- mset
- multi
- select

Besides these commands, Sidekiq requires pipelining, not sure if Dynomite can already do this.

**Comment by shailesh33** [comment]
Hi Jona,
brpop takes multiple list as arguments, now if your cluster has only 1 node
per rack, this would be fine but imagine, you have mulitple nodes per rack,
and one list is on node1 and other in node2, this is pretty much difficult
to support in Dynomite.
Also multi is another such command that will have adverse effects since
this is more like a distributed transactions in Dynomite which is not
supported at this time.

**Comment by jonakoudijs** [comment]
Hello Shailesh,

Thank you for your response. I understand the implications. I will check out the most closest alternative (for Sidekiq). I will close this issue seeing it is answered.
