### ISSUE TITLE
Query about the implementation of Gossip in Dynomite

### ISSUE THREAD

**Issue by scutpalmer** [Netflix/dynomite#473]
HI,
I am doing research on Gossip and related projects.

Since I cannot find much materials, can you help to explain the implementation of Gossip in Dynomite?

I wonder whether it is based on the paper of SWIM from Cornell, the Gossip implementation in Cassandra, or other ideas?
How about the Failure Detector, the choose of Anti-entropy/rumor mongering, Push/Pull/Push-Pull and so on.  

Thanks and Best Regards,

**Comment by shailesh33** [comment]
@timiblossom Can you please comment?

**Comment by shailesh33** [comment]
@scutpalmer we do not use gossip internally.The gossip code predates me so I am not an expert on commenting it but I believe it is based on the Cassandra style gossip.

**Comment by shailesh33** [comment]
by the way, if you are interested, you can improve the gossip here :) we will provide all the support needed.

**Comment by timiblossom** [comment]
Here is the capture of our conversation in case someone else is interested to contribute or looking for the answer:
## ChangHeng
I am doing research on Gossip and related projects.

Since I cannot find much materials, can you help to explain the implementation of Gossip in Dynomite?

I wonder whether it is based on the paper of SWIM from Cornell, the Gossip implementation in Cassandra, or other ideas?
How about the Failure Detector, the choose of Anti-entropy/rumor mongering, Push/Pull/Push-Pull and so on.

## Minh
We were thinking to implement Gossip style similar to what Cassandra has, which is SWIM.
However, since our infrastructure already has a process that can run on each box to check the health for
each local Dynomite process and record into our database (it is a Cassandra in this case).

We just piggybacked on this to use it as our Gossip replacement.  It is, even though being cumbersome with
extra pieces, it is very reliable in practice.

## ChangHeng
Really thanks a lot for your response.
 
I want to discuss it a bit more: as my understanding, you mean the Centralized membership management.
In general, the Centralized way will face the scalability issues, though it may function  better in small scale.
I think if we want to have a large cluster, say more than 1000 nodes, then it will be better to use the Gossip for membership management and update of other metadadas in a decentralized way.
 
Am I right?

## Minh
I think you are right to certain extend.  In our case, to support 1000 nodes, the central database/service needs only to support 1000 Writes per sec.  This write rate is very small to us actually.  I think we probably need around 200 writes/sec or smaller for such a cluster in most case because a node does not ping every sec.

I think using Gossip is simpler but there is some out-of-sync states that we need to deal with.

## ChangHeng
I see your conclusion.
 
Then I have a bit confusion, why so many projects(Dynamo, Cassandra, RingPop, Voldemort …) are using Gossip.
 
I guess normal user will use a cluster of above less than 100 nodes.

## Minh
I think Gossip would simplify the architecture.
In in theory, Gossip can scale more.  However, I never heard any company using C* cluster bigger than 1K nodes. I don't have the fact about Dynamo or Voldemort deployment.

In practice, Gossip does take a heavy load or resource on each node. Imaging in a 1K node cluster, every second each node has to process a significant number of incoming/outgoing Gossip pings and each Gossip ping contains 1000 nodes' metadata to process.  That is a lot of CPU cycles.

In Dynomite, it does expose an interface that you can plugin your own Gossip implementation.  Feel free to contribute.

**Comment by shailesh33** [comment]
@scutpalmer please reopen the issue if you have further questions. Thank you @timiblossom for your help. You are the best!
