### ISSUE TITLE
Drop-in replacement for Redis.

### ISSUE THREAD

**Issue by ashish235** [Netflix/dynomite#519]
Hi Team,

Sorry for asking such a noob question. I 'm actually in a hurry and need some urgent answer to fix some production issues caused due to geographical separation of my redis nodes. My setup has redis along with sentinels, a typical master slave architecture. 

Now I want to put dynomite instead of sentinel to manage the redis servers, so do I need any changes in my application? My application is in C. 

From reading the github readme pages, I didn't get the clarity on the application side changes to adapt to dynomite. Also for scaling if I understood correctly, I need a loadbalancer or something like twemproxy to distribute the load ?

Regards,
Ashish

**Comment by shailesh33** [comment]
You can still use your existing code to talk to "A Dynomite Node". Dynomite will forward the request to other nodes appropriately but you have to understand that when a node fails, the client should failover to another node. You will also have to design the topology, for example how many data centers, replicas etc. Dynomite doesnt auto scale yet, so its a good idea to pre-scale with growth in mind. You can always terminate one instance and bringer a larger node at its place. Go through the documentation.

**Comment by ashish235** [comment]
@shailesh33 , thanks for the reply. I did setup a scenario of 2 data centers for experiments, each having 1 node. Now the replication works both ways. When I create a n/w partition among these nodes, I did some random writes on both the sites and when the n/w partition is removed none of writes done to either of the sites is not getting replicated. So basically I 've a data mismatch. So the async way of replication to other site has a very limited timeout after which my writes won't be replicated. So out of CAPs, dynomite is implementing mainly A and P and not C. 

Did I understood it correctly or is I 'm doing something wrong here?

**Comment by shailesh33** [comment]
You got it correct. Systems like these depend on some reconciliation/repair process to sync up data.  We had a process internally that we started working but it is not PROD ready. The idea is basically to pull the data from mutliple nodes, compare and update the nodes so they are in sync. Hope this helps.

**Comment by axelfauvel** [comment]
Hello @shailesh33 : Do you plan to release the reconciliation tool someday ?

**Comment by shailesh33** [comment]
@ipapapa ^^

**Comment by ipapapa** [comment]
@axelfauvel It will take significant effort to release it. It also depends on external components like Spark. All Dynomite nodes send the data to a Spark cluster. The cluster finds the entropy and sends back the data with the newest timestamp. To be honest, it is not my favorite solution because it can be affected by clock skewness and requires a fork of Redis to keep timestamps, so I would prefer to see fresh ideas from the OSS. There are a few interesting opportunities with Redis modules.

**Comment by axelfauvel** [comment]
Thanks @ipapapa & @shailesh33 for the heads up and for all the work you've done :)

We're planning to use Dynomite to setup a multi-datacenter PHP session service. In our usecase, we won't have a very heavy load nor data volume. We plan to use the following architecture : 
* 3 DC
* 3 racks per DC
* 1 node per rack
* Each node seeds all cluster node **OR** each node seeds all DC nodes plus 1 node in every other DC (we haven't tested this yet)
* In each DC, Dynomite will be accessed through a round robin VIP. 

In case of a rack downtime, we are thinking of developing a 'warmup tool' that will : 
* Launch REDIS
* Launch Dynomite (to retrieve all new keys)
* Query its peers to see which one has a complete set of data
* Dumps all keys from the chosen peer
* Performs a SETNX (https://redis.io/commands/setnx) from the dump to insert keys that have not been altered since service started. This SETNX will be performed on REDIS node to avoid writing existing keys to the rest of the cluster.
* Records itself on the VIP

This can work because we only have one node per rack. 

What do you guys think of that ? Do you want me to release this tool when it will be complete ?

best

**Comment by ipapapa** [comment]
Just to clarify we do have a warm-up tool: https://github.com/Netflix/dynomite-manager/wiki/Cold-Bootstraping It has battle-tested for more than two years in production. This is effectively the first level of reconciliation. Hence we are covering the node terminations.

**Comment by ipapapa** [comment]
I am assuming since this question is a month old, it has been addressed.
