### ISSUE TITLE
Dynomite Functionality

### ISSUE THREAD

**Issue by nginxsantos** [Netflix/dynomite#530]
Hi,
Is the token management a functionality of Dynomite or Dynomite Manager.

Looking at the comments from @ipapapa , it seems the Token Management is done in Dynamite itself. Can someplease clarify on this. If it is done the Dynomite then does the default installation of Dynomite have it. If so, where do we store the tokens?

https://github.com/Netflix/dynomite/issues/342

What functionality will be missed if I am using dynomite without Dynomite Manager?

thanks, santos

**Comment by ipapapa** [comment]
Assuming a Dynomite node dies, and a new node comes up. There are two ways to achieve that the new node will take the same token, notify the rest of the nodes about its existence and join the ring. Gossip and static token management. There is a gossip protocol integrated with Dynomite but we do not use it on Netflix, hence we cannot guarantee 100% the reliability. If you are interested in contributing to and solidifying it, then that would be fantastic.

In our production systems, we use static token management. It scales better because you do not need to have a complicated algorithm for gossip and avoid a number of corner case issues that tend to appear in very large deployments. We follow the same approach in our Cassandra deployment. For token management, we store the tokens in a Cassandra cluster. This is a functionality integrated into the Dynomite Manager. We use Cassandra because it provides global replication. Hence, we have information about remote peer Dynomite nodes in all regions.

There are folks (to be honest several OSS users) that do not use Dynomite Manager (DM). @diegopacheco uses in Thomson Reuters DM. Some other companies have deployed a way to provide the seeds to the client from a REST call to Dynomite. The functionality you are going to miss is mentioned in the features of DM: https://github.com/Netflix/dynomite-manager/wiki/Features

**Comment by diegopacheco** [comment]
@nginxsantos 

I kind of code a simple version of my own token generator simulating the DM feature. However, I only did that because DM was no available, IF you already running on AWS like I'm, DM is the best solution. There are lots of other "procedural" tasks that DM does like Cold Bootstrap, S3 backups/restores that can be tricky to get it right so I would recommend use DM if you are in AWS. 

Some of my Dynomite experiences are captured here in this Meetup Netflix hosted in 2016 https://www.youtube.com/watch?v=Z4_rzsZd70o&feature=youtu.be I also do blog about dynomite here: http://diego-pacheco.blogspot.com.br/search?q=dynomite

I hope this helps you out somehow. 

Cheers,
Diego Pacheco

**Comment by thakurajayL** [comment]
HI,
Wanted to ask a question in continuation with the discussion.

If client gets to know that one of the node in rack has failed. Then what is suggested to shift all the traffic to other rack if available or shift the whole traffic to other data center if available ?

Also if the configuration used is single rack and multiple nodes then single node failure causes some disruption. So in that case what client should do, raise alarm & admin should bring up the failed node ?
Do we have provision to  provide the local HA within RACK by adding some redundant node ?

Thanks
Ajay

**Comment by ipapapa** [comment]
@thakurajayL clients should not talk across regions.  If they do, then your failure domains are not isolated. Hence, if a node fails and you have deployed 3 racks (RF=3) in each region, then you have two more nodes to failover in the same region (assuming your consistency level is DC_ONE). This can provide fairly good failover. We have observed that for caching solutions (RF=2) is also good enough but for databases where consistency is of importance, RF=3 is required.

If you deploy one rack and multiple nodes, then you can achieve partial HA. What if a rack or AZ is not available? We, therefore, suggest having multiple racks and each rack to contain at least one replica. This is a general recommendation. Its deployment has its own properties. Dynomite can be configured to run in any way you prefer.

In HA systems like Dynomite, there are no alarms. Node terminations happen so often and they should be treated as normal operations. The Dyno client will recognize that a node is down and will select another node to send the data. Once the new node is up it will be warmed up and will rejoin the ring.

**Comment by nginxsantos** [comment]
Hi @diegopacheco , @ipapapa ,

Thanks @diegopacheco for the greats links. It helps.

My requirement is a little different, I am working on a Telecom product which is not ready for the public cloud yet ( I have my own limitation). But, I am quite impressed with Dynomite. Great stuff guys :-)

I am thinking if I can't get the Dynomite Manager run in the OpenStack/KVM/vCenter in a short term, I have to go without it. I am also thinking to begin with I have to go without DM as I am afraid I can't make all the changes to DM to make it run in the private cloud.

My deployment needs to have local HA in same Data Center as well as Geographic Redundancy.

Dear @diegopacheco , 

Can you please share the Token Manager you wrote if there is no copy write issue. Where did you store the tokens ? 

How were you doing the Token Management, how were the clients getting those?

Did you have a local Token Manager and all Dynomite nodes learnt from it?

Please help in clarifying how you implemented it?

Thanks in advance. Looking forward to hear from you.

thanks, santos

**Comment by diegopacheco** [comment]
@nginxsantos 

We use NetflixOSS for ou cloud-native microservice stack and we use Archaius(https://github.com/Netflix/archaius) for conf management inside a microservice. However, Archaius does not place the config files inside your machine. So we have a configuration distribution solution which uses Git(http://gitblit.com/) to store property files and any other configuration files for Linux or the microservices stack. We have a Master/Slave architecture where we download the proper gitblit config repo from the near slave and clone the config repo on the proper node. We static generate the dynomite YAML files on the development time and store them on the proper gitblit repo. So when a dynomite node bootup we use aws user_data(in the end of the day it will be Linux os env vars) and we get the proper config for that Dynomite node. This solution works well for the server side, however, the clients need to be able to discover the cluster, so we start using AWS Route53(which is a DNS solution) in order to store cluster information there so clients could access the cluster. There were scripts on the /etc/init.d/ that update the IPs on the DNS when a node boot up, so IF a node dies the DNS would have the new IPs and the client will continue working. Later on, we move to Prana for cluster and client seeds discovery since Prana(https://github.com/Netflix/Prana) is able to register nodes on Eureka(https://github.com/Netflix/eureka). You could be using any or kind of distributed K/V store like Etcd(https://coreos.com/etcd/) or Consul(https://github.com/hashicorp/consul) or DNS(but DNS kind of sucks).  If you are interested in Prana I made a blog post with some instructions and a video showing how you could do the server part http://diego-pacheco.blogspot.com.br/2017/09/dynomite-eureka-registry-with-prana.html. Beware Netflix stop maintaining prana but IMHO is not a big deal. 

This solution kind of worked out for me for some time, however, there were the following issues:
   - Deploy topology was fixed, like always 3 nodes. 
   - There is no BackUp and cold bootstrap.  

There are 2 main use cases for dynomite: 1 - Cache and 2 - In-Memory Database. If you are using dynomite and cache you are fine you can code your poor man DM solution like I did However if you are using dynomite as an in-memory database(or your source of truth) you need Cold Bootstrap so If you are not using DM you need to code it. 

IMHO the best DM feature is the cold bootstrap. Because if a node dies DM goes to the "near" redis and copy live data. I did not code it that on my poor man DM solution thanks to @ipapapa  and his team that released DM so I could decommission mine in-house legacy solution. 

Here there is a pre-setup dynomite cluster you use to do developer test or even know how to configure the seeds. I use it all the time for tests :-)  https://github.com/diegopacheco/dynomite-docker .
I also made this simple project that is a kind of smoke integration test which verifies is the dynomite cluster is properly replicating data and I use it for telemetry purpose and deploy validation.
https://github.com/diegopacheco/dynomite-cluster-checker

Cheers,
Diego Pacheco

**Comment by ipapapa** [comment]
I am assuming this question has been addressed as there has been no follow up.
