### ISSUE TITLE
Dynomite without Dyno

### ISSUE THREAD

**Issue by mfouilleul** [Netflix/dynomite#98]
I'm testing Dynomite from several weeks now and my real issue is client side. I do not use Dyno client but just simple redis-cli or simple Redis drivers. 

Everything works well, perf increases linearly according to the number of nodes, replication is good too. I'm working now in HA, , as you do not have retry policy or failover strategy, when a node goes down, all the rack become unusable (because queries routed by the other nodes to its node will crash). We should work only on "sain" racks, to ensure consistency, we only work in one rack a time.

We usually use HAProxy for routing connections to our backend so I tried a schema like this:
```
frontend RING1
bind 0.0.0.0:6379
acl RING1-DC1-RC1_issue nbsrv(RING1-DC1-RC1) lt 2
use_backend RING1-DC1-RC2 if RING1-DC1-RC1_issue
default_backend RING1-DC1-RC1

backend RING1-DC1-RC1
option tcp-check
tcp-check send *1\r\n$4\r\nping\r\n
tcp-check expect string +PONG
balance leastconn
server DC1-RC1-R1 192.168.33.40:8102 check inter 100ms
server DC1-RC1-R2 192.168.33.41:8102 check inter 100ms

backend RING1-DC1-RC2
option tcp-check
tcp-check send *1\r\n$4\r\nping\r\n
tcp-check expect string +PONG
balance leastconn
server DC1-RC2-R3 192.168.33.42:8102 check inter 100ms
server DC1-RC2-R4 192.168.33.43:8102 check inter 100ms
```

Clients talk to the HAProxy through 6379, they are redirected to the rack RC1, if one node goes down in this rack, HAProxy routes queries on RC2 (HAProxy can be redunded with a VIP or something else).

I think it is really node expensive because if you have 40 nodes racks, when you loose one node you loose the rest of the rack (39) or if you have a ring of 2 racks your service goes down if you encouter an issue with one node in each rack. I would have your opinion on this topology, do I go in the wrong way?

Max.

**Comment by timiblossom** [comment]
@mfouilleul  when a node goes down on on rack and traffics reroute to another rack, this gives the administrator time to recover the 1st rack by bringing up that down node with warm data.  The probabability of having 2 down nodes, one on each rack, is small and we can always increase the number of racks to make this probability even smaller.  

Yeah, having HA is expensive because we have to store redundant copies of data.  If cost is the issue, you can use just one rack to front a database, then if a node is down, just let the traffics go directly to the database while you are fixing the down node(s). Since only a small traffics are allowed to hit the database, I think it should be ok for most cases.

**Comment by mfouilleul** [comment]
So my config sounds good?

**Comment by timiblossom** [comment]
It sounds good.  However, can traffics go back to RING1-DC1-RC1 after RING1-DC1-RC1 goes bad and you recover it?

**Comment by mfouilleul** [comment]
As soon as the RING1-DC1-RC1 is pingable haproxy routes the traffic to it. So we should care to make it pingable only if we recover the consistency (by playing with the /state commands).

I should test all this again and i think we will begin to setup a little rack soon.

Stay in touch.

Max
